replicaCount: 1

image: lkuzmicheva/order-service

service:
  type: ClusterIP
  port: 9003
  targetPort: web

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $1
  hosts:
    - host: arch.homework
      paths: ["/otusapp/kuzmicheva(/orders/.*|/orders$)"]

postgresql:
  url: jdbc:postgresql://postgresql:5432/postgres
  username: postgres
  password: postgres
