apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-service.fullname" . }}
  labels:
  {{- include "order-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "order-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "order-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
          env:
          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                name: order-service-secret
                key: username
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                name: order-service-secret
                key: password
          - name: spring.datasource.url
            value: {{ .Values.postgresql.url }}
          ports:
            - name: {{ .Values.service.targetPort }}
              containerPort: 8083
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
